# Generated by Django 4.1.7 on 2023-03-19 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='coins',
            new_name='coin',
        ),
    ]
